//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.CompareTours = new HashSet<CompareTour>();
            this.Favorites = new HashSet<Favorite>();
            this.TourImages = new HashSet<TourImage>();
        }
    
        public int TourID { get; set; }
        public int CategoryID { get; set; }
        public int CompanyID { get; set; }
        public int LocationID { get; set; }
        public string TourName { get; set; }
        public decimal Price { get; set; }
        public string Duration { get; set; }
        public string Departure { get; set; }
        public string Description { get; set; }
        public string Schedule { get; set; }
        public string Image { get; set; }
        public Nullable<int> MaxPeople { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompareTour> CompareTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourImage> TourImages { get; set; }
    }
}
